apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout
spec:
  replicas: 5
  strategy:
    canary:
      canaryService: canary-service
      stableService: stable-service
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {duration: 30}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-rollout
  template:
    metadata:
      labels:
        app: demo-rollout
    spec:
      containers:
      - name: demo-rollout
        image: argoproj/rollouts-demo:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
